### ISSUE TITLE
Please translate it to english

### ISSUE THREAD

**Issue by MeowedAt** [lt-name/MurderMystery_Nukkit_old#11]
Please translate it to english, it would help my server a lot.

**Comment by lt-name** [comment]
Sorry, my English is very poor and cannot be translated into English
But if you are interested, you can refer to this file to make an English language file
https://github.com/lt-name/MurderMystery_Nukkit/blob/master/src/main/resources/Resources/Language/zh_CN.yml

**Comment by lt-name** [comment]
I tried to use Google Translate to make English language files, but there are many errors that need to be corrected manually
